baseURL = "http://brewing.blackpine.io/"
languageCode = "en-us"
title = "Black Pine Brewing"
theme = "descent"

[params]
    headerTitle = "BLACK PINE"
    headerSubtitle = "brewing company"
    headerImage = "IMG_20180627_181331.jpg"
